# Use a base Node.js image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the root directory
COPY package*.json ./

# Install dependencies
RUN npm install --silent

# Copy all source files into the container
COPY . .

# Build the React application
RUN npm run build

# Expose the port on which the application will be accessible
EXPOSE 3000

# Start the React application
CMD ["npm", "start"]
