# Use a base Node.js image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json from the server directory
COPY package*.json ./

# Install dependencies
RUN npm install --silent

# Copy all source files into the container
COPY . .

# Expose the port on which the backend application will be accessible
EXPOSE 8000

# Start the backend application
CMD ["npm", "start"]
