apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: client
          image: oumaymaii/soutenance-app-client-jenkins:latest
        - name: server
          image: oumaymaii/soutenance-app-server-jenkins:latest

