apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-client
  template:
    metadata:
      labels:
        app: my-app-client
    spec:
      containers:
        - name: client
          image: oumaymaii/soutenance-app-client-jenkins:latest
          command: ["npm", "start"]
          stdin: true
          tty: true
          ports:
            - containerPort: 3000
