apiVersion: v1
kind: Service
metadata:
  name: my-app-server-service
spec:
  selector:
    app: my-app-server
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
